### ISSUE TITLE
MPC baseline

### ISSUE THREAD

**Issue by YandongJi** [google-research/motion_imitation#44]
Hi, I encountered the following error when compiling, are there any bugs or I didn't install correctly?
`Following is the error:
Traceback (most recent call last): File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main return _run_code(code, main_globals, None,
File "/usr/lib/python3.8/runpy.py", line 87, in _run_code exec(code, run_globals) 
File "/home/yandol/motion_imitation/motion_imitation/examples/mpc_example.py", line 153, in <module> app.run(main) 
File "/home/yandol/.local/lib/python3.8/site-packages/absl/app.py", line 303, in run _run_main(main, args)
 File "/home/yandol/.local/lib/python3.8/site-packages/absl/app.py", line 251, in _run_main sys.exit(main(argv)) 
File "/home/yandol/motion_imitation/motion_imitation/examples/mpc_example.py", line 149, in main _run_example() 
File "/home/yandol/motion_imitation/motion_imitation/examples/mpc_example.py", line 141, in _run_example hybrid_action, info = controller.get_action() 
File "/home/yandol/motion_imitation/mpc_controller/locomotion_controller.py", line 88, in get_action stance_action, qp_sol = self._stance_leg_controller.get_action() 
File "/home/yandol/motion_imitation/mpc_controller/torque_stance_leg_controller.py", line 179, in get_action motor_torques = self._robot.MapContactForceToJointTorques(leg_id, force) 
File "/home/yandol/motion_imitation/motion_imitation/robots/minitaur.py", line 695, in MapContactForceToJointTorques jv = self.ComputeJacobian(leg_id) 
File "/home/yandol/motion_imitation/motion_imitation/robots/laikago.py", line 249, in ComputeJacobian return super(Laikago, self).ComputeJacobian(leg_id)[(2, 0, 1), :] IndexError: index 2 is out of bounds for axis 0 with size 0`

**Comment by erwincoumans** [comment]
mpc_example is obsolete, use whole_body_control_example or locomotion_controller_example
