### ISSUE TITLE
ModuleNotFoundError: No module named 'locomotion'

### ISSUE THREAD

**Issue by HaojieSHI98** [google-research/motion_imitation#45]
When I want to use gym.
_env = gym.make('motion_imitation:A1GymEnv-v1', render=True)_
Error Occurred. I dont' know what's wrong with this, and wonder if someone could help fix it.

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/robot/anaconda2/envs/stone_legged/lib/python3.6/site-packages/gym/envs/registration.py", line 142, in make
    return registry.make(id, **kwargs)
  File "/home/robot/anaconda2/envs/stone_legged/lib/python3.6/site-packages/gym/envs/registration.py", line 87, in make
    env = spec.make(**kwargs)
  File "/home/robot/anaconda2/envs/stone_legged/lib/python3.6/site-packages/gym/envs/registration.py", line 58, in make
    cls = load(self.entry_point)
  File "/home/robot/anaconda2/envs/stone_legged/lib/python3.6/site-packages/gym/envs/registration.py", line 17, in load
    mod = importlib.import_module(mod_name)
  File "/home/robot/anaconda2/envs/stone_legged/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'locomotion'

**Comment by HaojieSHI98** [comment]
I have solved it, just modify the /motion_imitation/__init__.py as
register(
    env_id='A1GymEnv-v1',
    entry_point='motion_imitation.envs.gym_envs:A1GymEnv',
    max_episode_steps=2000,
    reward_threshold=2000.0,
)
